anneal_lr: true
batch_size: 8192
clip_coef: 0.2
clip_vloss: true
coef_align: 0.5
coef_collision: 10.0
coef_finish: 50.0
coef_gate: 10.0
coef_progress: 20.0
coef_smooth: 0.1
coef_spin: 0.1
coef_time: 0.05
config_file: level0_no_obst.toml
cuda: true
ent_coef: 0.01
gae_lambda: 0.95
gamma: 0.99
hidden_dim: 256
jax_device: gpu
learning_rate: 0.0003
max_grad_norm: 0.5
minibatch_size: 2048
n_history: 2
norm_adv: true
num_envs: 64
num_iterations: 2441
num_minibatches: 4
num_steps: 128
seed: 42
target_kl: null
torch_deterministic: true
total_timesteps: 20000000
update_epochs: 10
vf_coef: 0.5
wandb_entity: null
wandb_project_name: DroneRacing-PPO
