anneal_lr: true
batch_size: 98304
clip_coef: 0.2
clip_vloss: true
coef_align: 0.5
coef_collision: 10
coef_finish: 100
coef_gate: 10
coef_progress: 20
coef_smooth: 0.1
coef_spin: 0.1
coef_time: 0.05
config_file: level0_no_obst.toml
cuda: true
ent_coef: 0.007250811183323254
gae_lambda: 0.95
gamma: 0.98
hidden_dim: 256
jax_device: gpu
learning_rate: 0.0004895532181364697
max_grad_norm: 0.4
minibatch_size: 12288
n_history: 2
norm_adv: true
num_envs: 1024
num_iterations: 2034
num_minibatches: 8
num_steps: 96
seed: 123
target_kl: null
torch_deterministic: true
total_timesteps: 200000000
update_epochs: 12
vf_coef: 0.6
wandb_entity: null
wandb_project_name: DroneRacing-PPO
