anneal_lr: false
batch_size: 98304
clip_coef: 0.2
clip_vloss: true
coef_align: 0.5
coef_collision: 20
coef_finish: 100
coef_gate: 20
coef_progress: 50
coef_smooth: 0.0
coef_spin: 0.0
coef_time: 0
config_file: level2.toml
cuda: true
ent_coef: 0.005
gae_lambda: 0.95
gamma: 0.98
hidden_dim: 256
jax_device: gpu
learning_rate: 0.0001
max_grad_norm: 0.4
minibatch_size: 12288
n_history: 2
norm_adv: true
num_envs: 1024
num_iterations: 5086
num_minibatches: 8
num_steps: 96
seed: 42
stage: 2
target_kl: null
torch_deterministic: true
total_timesteps: 500000000
update_epochs: 12
vf_coef: 0.6
wandb_entity: null
wandb_project_name: DroneRacing-PPO
